server:
  port: 8081
  
## Application custom settings
custom:
  resource-server-url: http://localhost:8082/username
  
## KEYCLOAK
spring:
  security:
    oauth2:
      client:
        registration:
          ## Authorization code client
          oauth2-client-ac:
            client-id: oauth2-client
            client-name: oauth2-client-ac
            client-secret: CHANGE-ME
            scope:
            - openid
            - profile
            - roles
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/oauth2-client
          ## Client credentials client
          oauth2-client-cc:
            client-id: oauth2-client
            client-name: oauth2-client-cc
            client-secret: CHANGE-ME
            authorization-grant-type: client_credentials
        provider:
          oauth2-client-ac:
            issuer-uri: http://localhost:8080/realms/SpringBootKeycloak
            user-info-uri: http://localhost:8080/realms/SpringBootKeycloak/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
          oauth2-client-cc:
            token-uri: http://localhost:8080/realms/SpringBootKeycloak/protocol/openid-connect/token

## LOGGING
#logging:
#  level:
#    root: DEBUG