version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.1
    command:
      - "start-dev"
      - "--import-realm"
    ports:
      - "8080:8080"
    volumes:
      - ./realm-import.json:/opt/keycloak/data/import/realm-import.json
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-import.json